[tool.isort]
sections = ['FUTURE', 'STDLIB', 'THIRDPARTY', 'FIRSTPARTY', 'LOCALFOLDER']
known_local_folder = ["jirabot"]

[tool.pyright]
include = ["src"]

# [tool.pytest.ini_options]
# log_cli = true
# log_cli_level = "INFO"
# log_cli_format = "%(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)"
# log_cli_date_format = "%Y-%m-%d %H:%M:%S"
# testpaths = [
#     "test",
# ]
# pythonpath = ["src"]