name: BuildBinary

on: workflow_dispatch

jobs:
  build_bot:
    runs-on: ubuntu-latest
    outputs:
      output1: build
    container:
      image: python:3.11.4
    steps:
      - uses: actions/checkout@v3
      - name: Build JiraBot
        run: ./scripts/build.sh
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Utils
          path: dist/*